Feature#63 client encapsulation
kolyasalubov/ProjectShop pull request #101
Opened 2021-09-17 12:09 UTC by v-lavrushko

documentation and error status code handling will come later
there are also commits from the hotfix_1 branch, ignore them

2021-09-19 21:51 UTC, v-lavrushko commented
Update: now adjusted to Pydantic

2021-09-20 10:48 UTC, strangerok1507 requested changes

2021-09-20 10:48 UTC, strangerok1507 commented on TelegramBot/client/models.py
> +        response = bot_client.send_request("GET", f"user/{user_id}/wishlist")
нужно в будущем учитывать что на страничуках LIST  есть пагинация, можно тикетом отдельным сделать

2021-09-20 10:48 UTC, strangerok1507 commented on TelegramBot/client/models.py
> +            return [cls(**c) for c in response.json()]
тоже самое, нужно сделать гет с пагинацией(опять же давайте тикетом отдельным сделаем и в дальнейшем решим эту проблему)

2021-09-20 10:48 UTC, strangerok1507 commented on TelegramBot/requirements.txt
> +Django==3.2.6
как ты создавал requirements.txt? pip freeze > requirements.txt ? зачем тут джанго?

2021-09-20 10:58 UTC, v-lavrushko commented on TelegramBot/client/models.py
> +        response = bot_client.send_request("GET", f"user/{user_id}/wishlist")
как это сделать тикетом?

2021-09-20 11:49 UTC, strangerok1507 commented on TelegramBot/client/models.py
> +        response = bot_client.send_request("GET", f"user/{user_id}/wishlist")
создать задачу и поместить её в беклог

2021-09-20 12:25 UTC, v-lavrushko commented
@strangerok1507 готово

2021-09-22 20:04 UTC, OlehHnyp commented on TelegramBot/client/models.py
> +        return response == 200
```suggestion
        return response.status_code == 200
```

2021-09-22 20:04 UTC, OlehHnyp commented on TelegramBot/client/models.py
> +        return response == 200
```suggestion
        return response.status_code == 200
```

2021-09-22 20:07 UTC, OlehHnyp commented on TelegramBot/client/models.py
> +        if response == 200:
```suggestion
        if response.status_code == 200:
```

2021-09-22 20:09 UTC, OlehHnyp commented on TelegramBot/client/models.py
> +        return response == 201
```suggestion
        return response.status_code == 201
```

2021-09-22 21:46 UTC, v-lavrushko commented
@OlehHnyp thanx, now done

2021-09-23 15:51 UTC, strangerok1507 approved these changes

2021-09-23 16:11 UTC, ruslanliska approved these changes

2021-09-23 16:34 UTC, merged