Connect order and order items
kolyasalubov/ProjectShop pull request #106
Opened 2021-09-20 14:35 UTC by ruslanliska

Deleted orderitems model and connected itself to order, Also created migrations for shippingmodel and updated order for api view
Closes #104

2021-09-20 17:56 UTC, v-lavrushko requested changes
Where is OrderItems?

2021-09-20 17:56 UTC, v-lavrushko commented on ProjectShop/order/models.py
> +class OrderModel(models.Model):
Why OrderModel and not Order?

2021-09-20 17:56 UTC, v-lavrushko commented on ProjectShop/order/models.py
> +# from ProductApp.models import Product
You probably can uncomment this

2021-09-20 17:56 UTC, v-lavrushko commented on ProjectShop/order/models.py
> +    order_items_qantity = models.PositiveIntegerField(verbose_name=_("Quantity"))
What's this?

2021-09-21 05:33 UTC, ruslanliska commented on ProjectShop/order/models.py
> +class OrderModel(models.Model):
> Why OrderModel and not Order?

Перейменував щоб не було зациклення, яке було раніше (from order.models import order) вибивало помилку через одинакові назви @v-lavrushko

2021-09-21 05:33 UTC, ruslanliska commented on ProjectShop/order/models.py
> +# from ProductApp.models import Product
> You probably can uncomment this

Напевно так, але в продукті є помилка, яку треба пофіксити, інакше нічого не працює

2021-09-21 05:34 UTC, ruslanliska commented on ProjectShop/order/models.py
> +    order_items_qantity = models.PositiveIntegerField(verbose_name=_("Quantity"))
> What's this?

Це змінна яка була в ордерітемс, яку просто переніс в ордер

2021-09-21 05:37 UTC, ruslanliska commented
> Where is OrderItems?

В моделі ордерітемс було тільки два поля: Кількість і продукт
Їх було перенесено в ордер, а апка видалена

2021-09-21 06:33 UTC, v-lavrushko commented
> > Where is OrderItems?
> 
> 
> 
> В моделі ордерітемс було тільки два поля: Кількість і продукт
> 
> Їх було перенесено в ордер, а апка видалена
> 
> 

А як тепер дотриматися відповідності продукт – кількість?

2021-09-21 06:37 UTC, strangerok1507 commented on ProjectShop/order/views.py
> +    queryset = OrderModel.objects.all()
метод удаления для OrderModel может переписать на изменение статуса "DELETED"

2021-09-21 10:15 UTC, ProkhvatylovArtem commented on ProjectShop/order/models.py
> -    order_items = models.ForeignKey(OrderItems, on_delete=CASCADE)
Mistake. Should be models.CASCADE

2021-09-22 07:27 UTC, OlehHnyp commented on ProjectShop/ProjectShop/urls.py
> +    path("api/", include("order.urls")),
Пропоную змінити шлях на "order_api" наприклад, щоб була назва апки, і щоб можна було зробити аналогічно для решти апок ("user_api", "product_api").

2021-09-22 07:29 UTC, ruslanliska commented on ProjectShop/ProjectShop/urls.py
> +    path("api/", include("order.urls")),
Покажу на зустрічі як це виглядає, і подумаємо


> Пропоную змінити шлях на "order_api" наприклад, щоб була назва апки, і щоб можна було зробити аналогічно для решти апок ("user_api", "product_api").

2021-09-22 08:39 UTC, OlehHnyp commented on ProjectShop/ProjectShop/urls.py
> +    path("api/", include("order.urls")),
Супер, дякую.

2021-09-22 08:40 UTC, OlehHnyp approved these changes
Looks good.

2021-09-22 08:41 UTC, MykhailoGrynenko approved these changes

2021-09-22 08:43 UTC, v-lavrushko approved these changes

2021-09-22 08:44 UTC, merged