Feature #128 common router for API root
kolyasalubov/ProjectShop pull request #129
Opened 2021-09-23 16:45 UTC by ruslanliska

closes #128

2021-09-24 20:29 UTC, Maxgioman approved these changes

2021-09-26 08:23 UTC, strangerok1507 approved these changes

2021-09-26 10:22 UTC, ProkhvatylovArtem requested changes

2021-09-26 10:22 UTC, ProkhvatylovArtem commented on ProjectShop/ProjectShop/urls.py
> +    path('api/v1/', include(router.urls)),
If I'm not mistaken, we need to use quotes in the include.

2021-09-27 07:34 UTC, ruslanliska commented on ProjectShop/ProjectShop/urls.py
> +    path('api/v1/', include(router.urls)),
В цьому випадку ми імпортимо сам роутер і даємо шлях до його інстансу urls
В лапках вказуємо якщо є ім'я файлу (як було раніше)

> If I'm not mistaken, we need to use quotes in the include.

2021-09-27 07:51 UTC, OlehHnyp approved these changes
LGTM

2021-09-27 09:23 UTC, MykhailoGrynenko approved these changes
LGTM

2021-09-27 09:24 UTC, ProkhvatylovArtem approved these changes

2021-09-27 09:25 UTC, merged