Feature#83_Create_tests_for_all_models
kolyasalubov/ProjectShop pull request #145
Opened 2021-09-29 06:31 UTC by CheshirLvova

Feature#144-tests_for_shipping_model

2021-09-29 08:34 UTC, strangerok1507 commented on ProjectShop/order/tests/tests.py
> +
rename this file to test_models

2021-09-29 08:34 UTC, strangerok1507 commented on ProjectShop/Shipping/tests/tests.py
> +
rename this file to test_models

2021-09-30 08:22 UTC, v-lavrushko commented on ProjectShop/order/tests/factories.py
> +    order_items_qantity = factory.Faker('random_int', min=1, max=100)
*quantity

2021-09-30 08:22 UTC, v-lavrushko commented on ProjectShop/order/tests/tests.py
> +        self.assertIsNotNone(OrderItems)
PEP 8 - blank line

2021-10-04 11:13 UTC, MykhailoGrynenko commented on ProjectShop/Shipping/tests/tests.py
> +        self.assertIsNotNone(shipping)
It seems like there is an indentation issue. What is the purpose of the setUp method, which does nothing?
![Screenshot from 2021-10-04 14-10-50](https://user-images.githubusercontent.com/56480204/135841630-d86df8cc-bd73-482b-986b-317100e4b030.png)

2021-10-04 11:14 UTC, MykhailoGrynenko commented on ProjectShop/Shipping/tests/tests.py
> +
So many blank lines over here.

2021-10-04 11:15 UTC, MykhailoGrynenko commented on ProjectShop/order/tests/factories.py
> +from order.models import OrderItemsModel
from order.models import OrderModel, OrderItemsModel

2021-10-04 11:18 UTC, MykhailoGrynenko commented on ProjectShop/Shipping/tests/tests.py
> +from Shipping.tests.factories import *
I believe importing an asterisk is not the best practice.

2021-10-04 11:20 UTC, MykhailoGrynenko requested changes
Changes requested.

2021-10-05 16:31 UTC, strangerok1507 commented on ProjectShop/Shipping/tests/factories.py
> +    postal_code = factory.Faker('45678')
что за провайдер 45678?

2021-10-12 21:19 UTC, CheshirLvova commented on ProjectShop/order/tests/factories.py
> +from order.models import OrderItemsModel
done)

2021-10-12 21:21 UTC, CheshirLvova commented on ProjectShop/order/tests/factories.py
> +    order_items_qantity = factory.Faker('random_int', min=1, max=100)
fixed

2021-10-12 21:21 UTC, CheshirLvova commented on ProjectShop/order/tests/tests.py
> +
done)

2021-10-13 09:37 UTC, v-lavrushko approved these changes

2021-10-19 19:12 UTC, Maxgioman commented on ProjectShop/Shipping/tests/test_models.py
> +        self.assertEqual(shipping.country, shipping.__str__())
як у нас один і той же метод __str__() видає три різні варіанти в 3 тестах і всі правильні?

2021-11-15 16:35 UTC, ProkhvatylovArtem approved these changes

2021-11-17 07:34 UTC, merged