Feature x26 password reset email
kolyasalubov/ProjectShop pull request #57
Opened 2021-09-08 07:39 UTC by MykhailoGrynenko

Password reset functionality via email has been added.

2021-09-08 17:57 UTC, OlehHnyp reviewed
I tried to reset password and received email with link to "Example Domain".
I didn't succeed to reset password.  
How about asking more information(phone number, first name, last name)  before sending password-reset email?

2021-09-17 11:58 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/urls.py
> +         name='password_reset'),
Дякую. Зробив зміни. Прошу перевірити.

2021-09-17 12:05 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +    success_message = "Congratulations! Your account has been created. You may sign in!"
Дякую.
Начебто достатньо цього:
from django.utils.translation import ugettext_lazy as _
success_message = _("Congratulations! Your account has been created. You may sign in!")
![Screenshot from 2021-09-17 15-02-56](https://user-images.githubusercontent.com/56480204/133779856-89479dc4-29b1-4b53-b2f5-4999aca22af8.png)

Чи краще зробити через метод get_success_message?

2021-09-19 06:13 UTC, strangerok1507 requested changes

2021-09-19 06:13 UTC, strangerok1507 commented on ProjectShop/UserApp/views.py
> +    success_message = "Congratulations! Your account has been created. You may sign in!"
success_message = _("Congratulations! Your account has been created. You may sign in!")
всё супер)

2021-09-20 10:06 UTC, strangerok1507 approved these changes
LGTM +1

2021-09-20 10:41 UTC, v-lavrushko commented
closes #23 
closes #26

2021-09-20 10:42 UTC, merged