Feature x49 create profile and update page
kolyasalubov/ProjectShop pull request #80
Opened 2021-09-12 15:07 UTC by MykhailoGrynenko

2021-09-14 07:35 UTC, OlehHnyp approved these changes
LGTM

2021-09-15 12:12 UTC, v-lavrushko approved these changes

2021-09-20 06:40 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/forms.py
> +        fields = ('email', 'phone_number', 'first_name', 'last_name', 'birth_date')
Thanks. Done.

2021-09-20 06:40 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +    success_message = "Congratulations! Your account has been created. You may sign in!"
Thanks. Done.

2021-09-20 06:40 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +class RegisterView(SuccessMessageMixin, generic.CreateView):
Thanks. Done.

2021-09-20 06:40 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +class LoginView(auth_views.LoginView):
Thanks. Done.

2021-09-20 07:04 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +def profile(request):
Пробував використати generic.UpdateView. Воно хоче sllug або pk.Тобто, шлях:
path('profile/<pk>', ... )
Так розумію, має бути: path('profile/',)
Мабуть UpdateView не підоходить тут. Не знаю як це реалізувати через Class based view

2021-09-20 10:38 UTC, strangerok1507 requested changes

2021-09-20 10:38 UTC, strangerok1507 commented on ProjectShop/UserApp/views.py
> +def profile(request):
самый простой вариант, как раз таки использовать PK, можно ещё попробовать в self.dispatch задавать self.kwargs

2021-09-20 15:58 UTC, MykhailoGrynenko commented on ProjectShop/UserApp/views.py
> +def profile(request):
З допомогою VladKriuch редагування профілю написано через клас.
Може LoginRequiredMixin краще імпортувати з braces.views

2021-09-21 06:32 UTC, strangerok1507 approved these changes

2021-09-21 09:09 UTC, merged