Hotfix 1
kolyasalubov/ProjectShop pull request #95
Opened 2021-09-16 11:43 UTC by v-lavrushko

migration directories with __init__.py files need to exist for migrations to work!
some small tweaks in ProductApp app (initially, it wasn't even added to settings.py)

2021-09-16 12:00 UTC, OlehHnyp approved these changes

2021-09-16 18:20 UTC, strangerok1507 requested changes

2021-09-16 18:20 UTC, strangerok1507 commented on .gitignore
> +*/migrations/*
убери это из гитигнора. миграции должны создаваться и использоваться на дев машинах. они должны быть управляемыми

2021-09-17 19:19 UTC, ProkhvatylovArtem approved these changes

2021-09-19 06:15 UTC, strangerok1507 requested changes

2021-09-19 06:15 UTC, strangerok1507 commented on TelegramBot/models.py
> +class Model:
зачем отдельный класс Model?

2021-09-20 10:42 UTC, strangerok1507 commented on TelegramBot/models.py
> +class Model:
вопрос остаётся актуальным. для валидации будем использовать Pydantic.

2021-09-20 11:01 UTC, v-lavrushko commented on TelegramBot/models.py
> +class Model:
удалил. Оно даже не должно было там быть

2021-09-20 11:48 UTC, strangerok1507 approved these changes

2021-09-20 12:24 UTC, merged